### ISSUE TITLE
Option to skip or hide unprocessed captures

### ISSUE THREAD

**Issue by mihow** [RolnickLab/antenna#585]
In the session detail view, it can be tricky (and confusing) to navigate to frames that have detections ready to view. An option to ignore the unprocessed captures would be helpful. I propose:

- A checkbox titled "Skip unprocessed" next to the prev/next navigation buttons 
 - Checked by default
 - When enabled, it disabled the ability to click on an unprocessed capture in the timeline
 - When enabled, the next/prev & keyboard navigation skip to the next processed captured
 - When the session detail page loads and no capture is specified in the URL, load the first processed capture (The backend likely needs to return this)

![image](https://github.com/user-attachments/assets/8d48d2f1-80bf-4dc8-ba3b-8d49aa04ae50)

@rhine3 @annavik  thoughts?

**Comment by rhine3** [comment]
This looks great! Would definitely make sessions easier for me to navigate. Here are a couple additional suggestions you can take or leave.

- People might not see the automatically-checked box and may wonder why their session appears to only have, say, 40 images. I wonder if somewhere on the session page, you could also add a legend in the same style as the legend that's displayed when you hover over the timeline, but one that represents overall stats for the session. For example, it could show the total number of captures in the session, the total number of processed captures, and the average number of detections per processed capture

- If images in the session have been processed by multiple pipelines: should it display any processed image, or only images processed by a particular pipeline? Is there a way to tell which images were processed by which pipeline, e.g. maybe using additional colors besides the blue to indicate them?

**Comment by annavik** [comment]
Hi @mihow and @rhine3 ! I have started to look into this a bit :) See #596 
- I followed your suggestions Michael, with some small logic adjustments due to some limitations in the backend response. Also I placed the control alongside other view settings.
- Good point Tessa with the session overview! In my suggestion, I kept the graph as is, to keep this overview. Just updated the navigation behaviour, what do you think?
- For images that has been processed by multiple pipelines, I think it requires a bit of more work! Currently we are fully prepared to handle this on the frontend side, as you might have noticed. Also I will need to have a chat with Michael about the BE status for this. I will create a separate issue about this, thanks for bringing it up! :)

**Comment by mihow** [comment]
closed by #596
